### ISSUE TITLE
need a sample:  how to use helper functions to add a header

### ISSUE THREAD

**Issue by figuerres** [gund/ng2-http-interceptor#102]
i see the helper functions but i am lost on how i am supposed to use them inside the interceptor to add a header.
or should i be calling a whole different method at the start ??

a small demo would be great!

**Comment by gund** [comment]
Sure, consider we have a request interceptor:
```ts
httpInterceptor.request().addInterceptor((data, method) => {
  const headers = getHttpHeadersOrInit(data, method); // Get or create header and set back on `data`
  headers.append('X-Header-Foo', 'bar'); // Do whatever you need with the `Headers` object
  return data;
})
```

NOTE: With this function you do not really need to assign headers back on `data` since it will do it for you even if headers were not provided originally.

Hope that helped =)

**Comment by figuerres** [comment]
ok i get a compile error that the function is not found.
i am guessing that i need an import ???

**Comment by gund** [comment]
Yes, just import it same as you do with `HttpInterceptor` like so:
```ts
import { HttpInterceptor, getHttpHeadersOrInit } from 'ng2-http-interceptor';
```

**Comment by figuerres** [comment]
ahhh, i have been importing classes but never knew i could use that on a function till now...

**Comment by gund** [comment]
You can do that as well with `const`/`let` and even `var` =)
