### ISSUE TITLE
Cannot find name 'ProxyHandler'.

### ISSUE THREAD

**Issue by jorawarsingh** [gund/ng2-http-interceptor#24]
Any guess what it can be? i am using webstorm and if i do ctrl+click on ProxyHandler i can go to the declaration in typescript/lib/lib.es2015.proxy.d.ts

**Comment by gund** [comment]
That's totally fine since class ProxyHandler is part of standard library and it's location in file like that can tell you about it.

**Comment by gund** [comment]
Well that's interesting. Are you using it in project generated via angular-cli?
Maybe you can share your tsconfig.json?

**Comment by dondimon** [comment]
I'm getting same issue - using Angular 2.1.1... can't build either.. can't build with either tsc or visual studio TS compiler.

node_modules/ng2-http-interceptor/dist/http/interceptable-http-proxy.service.d.ts(3,63): error TS2304: Cannot find name 'ProxyHandler'.

**Comment by gund** [comment]
Well as far as I can see it seems that your TS compiler does not support ES6 typings.
You can try to upgrade it to version 2.0.1.
Or if that does not help you can go and get [this typing file](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts), put it in your project and reference in your entry point *.ts file.

**Comment by jorawarsingh** [comment]
I'm targeting es5. I have tried to target es6 but it seems to be many issues with that so till they are resolved i have to stick to es5. 
https://github.com/Microsoft/TypeScript/issues/3215
https://github.com/angular/angular/issues/4882

**Comment by gund** [comment]
@jorawarsingh so if you target ES5 this issue gone?

**Comment by jorawarsingh** [comment]
No, still remain.

**Comment by gund** [comment]
Can you please try to compile with next options in tsconfig.json:
_compilerOptions_ -> _lib_: ["es6", "dom"]
_compilerOptions_ -> _module_: "es6"

I'm also targeting ES5 but don't have this issue so probably those settings might resolve them.

**Comment by gund** [comment]
Today I made use of this library in different project and experienced same issue so was able to check by myself how to fix this.
And yes `compilerOptions -> lib: ["es6"]` is the key point here - it tells TS compiler to include es6 type definitions in the project.

However in my particular case there where some external libs which were not able to compile with this configuration so in this case I left config as is and added next line to my _custom definitions_ file:
```ts
declare interface ProxyHandler<T> {}
```
That fixed issue as well.
