### ISSUE TITLE
inject headers to all requests

### ISSUE THREAD

**Issue by ujibang** [gund/ng2-http-interceptor#35]
is it possible/planned to inject headers to the requests?

my use case is the following: basic authentication + auth data stored via redux. I would like to intercept all request and inject the Authorization header.

**Comment by gund** [comment]
Hi,

I believe your question was already answered in issue #23

Please check that out and if you will have more questions you can go ahead and ask them here.

As for now I'm closing this one. Thanks.

**Comment by ujibang** [comment]
yes that was exactly what I needed, it works like a charm.

great package!
